### ISSUE TITLE
MappingUpdater error

### ISSUE THREAD

**Issue by Ambrosiani** [NordicMuseum/Wikimedia-Commons-uploads#24]
Traceback (most recent call last):
  File "importer/DiMuMappingUpdater.py", line 532, in <module>
    main()
  File "importer/DiMuMappingUpdater.py", line 526, in main
    updater = DiMuMappingUpdater(options)
  File "importer/DiMuMappingUpdater.py", line 76, in __init__
    self.dump_to_wikifiles()
  File "importer/DiMuMappingUpdater.py", line 80, in dump_to_wikifiles
    self.dump_places()
  File "importer/DiMuMappingUpdater.py", line 100, in dump_places
    merged_places, preserved_places = ml.multi_table_mappings_merger(
AttributeError: 'MappingList' object has no attribute 'multi_table_mappings_merger'
<class 'AttributeError'>

**Comment by Ambrosiani** [comment]
nvm jag gissar att jag ska uppgradera batchuploadtools först
