### ISSUE TITLE
mapping error

### ISSUE THREAD

**Issue by Ambrosiani** [NordicMuseum/Wikimedia-Commons-uploads#41]
hej @lokal-profil @Vesihiisi om ni känner för det får ni gärna hjälpa mig reda ut ett fel i mappingupdater – det här felmeddelandet får jag när jag försöker mappa Armémuseums bilder.

Jag kör mot mappen https://digitaltmuseum.se/021098287216/armemuseum-pa-wikimedia-commons

```
IT181126D:Wikimedia-Commons-uploads arona$ python3 importer/DiMuMappingUpdater.py 
Loaded all mappings
Created mappings/commons-places.json
Traceback (most recent call last):
  File "importer/DiMuMappingUpdater.py", line 536, in <module>
    main()
  File "importer/DiMuMappingUpdater.py", line 530, in main
    updater = DiMuMappingUpdater(options)
  File "importer/DiMuMappingUpdater.py", line 76, in __init__
    self.dump_to_wikifiles()
  File "importer/DiMuMappingUpdater.py", line 80, in dump_to_wikifiles
    self.dump_places()
  File "importer/DiMuMappingUpdater.py", line 101, in dump_places
    self.places_to_map, update=True)
  File "/usr/local/lib/python3.7/site-packages/batchupload/listscraper.py", line 325, in multi_table_mappings_merger
    update=update)
  File "/usr/local/lib/python3.7/site-packages/batchupload/listscraper.py", line 277, in mappings_merger
    name = entry.pop(name_key)
AttributeError: 'NoneType' object has no attribute 'pop'
CRITICAL: Exiting due to uncaught exception <class 'AttributeError'>
```

**Comment by lokal-profil** [comment]
Assuming no deeper issues (differences between how Python versions deal with collections) it looks like maybe the night be an issue with the old being empty? Can you see what places are being extracted from the data without taking the pte-existing list into account (iirc there is s flag for that).

I've only looked at the code quickly on my mobile,  limited to no laptop access

**Comment by lokal-profil** [comment]
Looked into this a bit further (after an additional ping from @jhsoby ). This is caused by bad data in the image. In @jhsoby by there being a `depictedPlaces` entry without a value (see e.g. F42D9D41-4166-4A89-A277-B58BA59EDB07).

I'll put together a patch which skips mapping these but reports them to the command line in case you want to upstream the issue.
